version: "3.7"

services:
  rss_db:
    container_name: rss_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
       - rss_db:/data/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - rss
    restart: unless-stopped

  rss_testdb:
    container_name: rss_testdb
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      PGDATA: /data/postgrestest
    volumes:
       - rss_testdb:/data/postgrestest
    ports:
      - "${POSTGRES_TEST_PORT}:${POSTGRES_PORT}"
    networks:
      - rss
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"
    volumes:
     - redis_data:/var/lib/redis
    networks:
      - rss
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rss
    volumes:
      - rabbit_data:/data/rabbitmq

networks:
  rss:

volumes:
  rss_db:
  rss_testdb:
  redis_data:
  rabbit_data:
